version: '3'

services:
    builder:
        image: ${BUILD_BASE_DOCKER_IMAGE}
        container_name: ${TEST_CONTAINER_NAME}
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        environment:
            PYTHON37_VERSION: ${PYTHON37_VERSION}
        security_opt:
            - apparmor:unconfined
            - seccomp:unconfined
        tmpfs:
            - /run
            - /run/lock
            - /tmp
        tty: true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - /lib/modules:/lib/modules:ro
            - ./:${BUILD_CONTAINER_WORK_DIR}:rw
        working_dir: ${BUILD_CONTAINER_WORK_DIR}
