---
platform: linux

image_resource:
    type: docker-image
    source:
        repository: codeghar/snapcraft
        tag: latest

inputs:
    - name: snap-python37-src

outputs:
    - name: snap-python37-artifacts

run:
    path: ./snap-python37-src/ci/concourse/build.sh
